package com.test.jobs.util

import com.test.jobs.model.Job

class MockJobsDataUtil {
    companion object {
        fun getMockData(): List<Job> {
            return listOf(
                Job(
                    "UI Researcher",
                    "Pinterest",
                    "45",
                    "Placeholder",
                    "Permanent",
                    23,
                    "Travel paid, Breaks paid, Parking paid",
                    "Full time",
                    "Full time",
                    2,
                    "250",
                    "19.11.2023",
                    "23",
                    "+1 929 303 45 56",
                    "Ann",
                    "Native",
                    "Intermediate",
                    "Medium",
                    "Vacancy only for students"
                ),
                Job(
                    "UI Researcher",
                    "Pinterest",
                    "45",
                    "Placeholder",
                    "Permanent",
                    23,
                    "Travel paid, Breaks paid, Parking paid",
                    "Full time",
                    "Full time",
                    2,
                    "250",
                    "19.11.2023",
                    "23",
                    "+1 929 303 45 56",
                    "Ann",
                    "Native",
                    "Intermediate",
                    "Medium",
                    "Vacancy only for students"
                ),
                Job(
                    "UI Researcher",
                    "Pinterest",
                    "45",
                    "Placeholder",
                    "Permanent",
                    23,
                    "Travel paid, Breaks paid, Parking paid",
                    "Full time",
                    "Full time",
                    2,
                    "250",
                    "19.11.2023",
                    "23",
                    "+1 929 303 45 56",
                    "Ann",
                    "Native",
                    "Intermediate",
                    "Medium",
                    "Vacancy only for students"
                ),
                Job(
                    "UI Researcher",
                    "Pinterest",
                    "45",
                    "Placeholder",
                    "Permanent",
                    23,
                    "Travel paid, Breaks paid, Parking paid",
                    "Full time",
                    "Full time",
                    2,
                    "250",
                    "19.11.2023",
                    "23",
                    "+1 929 303 45 56",
                    "Ann",
                    "Native",
                    "Intermediate",
                    "Medium",
                    "Vacancy only for students"
                ),
                Job(
                    "UI Researcher",
                    "Pinterest",
                    "45",
                    "Placeholder",
                    "Permanent",
                    23,
                    "Travel paid, Breaks paid, Parking paid",
                    "Full time",
                    "Full time",
                    2,
                    "250",
                    "19.11.2023",
                    "23",
                    "+1 929 303 45 56",
                    "Ann",
                    "Native",
                    "Intermediate",
                    "Medium",
                    "Vacancy only for students"
                ),
                Job(
                    "UI Researcher",
                    "Pinterest",
                    "45",
                    "Placeholder",
                    "Permanent",
                    23,
                    "Travel paid, Breaks paid, Parking paid",
                    "Full time",
                    "Full time",
                    2,
                    "250",
                    "19.11.2023",
                    "23",
                    "+1 929 303 45 56",
                    "Ann",
                    "Native",
                    "Intermediate",
                    "Medium",
                    "Vacancy only for students"
                ),
            )
        }
    }
}